# -*- coding: utf-8 -*-
"""VizualizaçãodeDadosPandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sD2IoFesvoQop8ZtWyTx2hq2KBx0fH34
"""

import matplotlib.pyplot as plt
import pandas as pd
import csv

dataset_d = pd.read_csv('breast_cancer.csv')
dataset_d.columns
dataset_d

def desenhaDiagnostico(data):
    colors = {2: 'blue', 4: 'red'} #dicionário de cores para cada diagnóstico

    x_values = data['Uniformity of Cell Size'].unique()
    y_values = data['Uniformity of Cell Shape'].unique()

    fig, ax = plt.subplots()# Cria uma figura e um conjunto de eixos

    # Itera sobre os valores únicos
    for x in x_values:
        for y in y_values:
            diagnosis = data[(data['Uniformity of Cell Size'] == x) & (data['Uniformity of Cell Shape'] == y)]['Class'].values
            if len(diagnosis) > 0:
                diagnosis = diagnosis[0]
                color = colors[diagnosis]
                count = data[(data['Uniformity of Cell Size'] == x) & (data['Uniformity of Cell Shape'] == y)].shape[0]
                marker_size = count * 5  # Aumenta o tamanho proporcionalmente ao número de entradas iguais
                ax.scatter(x, y, color=color, s=marker_size)

    # labels
    ax.set_xlabel('Uniformity of Cell Size')
    ax.set_ylabel('Uniformity of Cell Shape')
    ax.set_title('Diagnóstico do Câncer de Mama')

    plt.show()
desenhaDiagnostico(dataset_d)